###
# Upload the data to an EBS volume and snapshot it.

require 'catpaws'

#generic settings
set :aws_access_key,  ENV['AMAZON_ACCESS_KEY']
set :aws_secret_access_key , ENV['AMAZON_SECRET_ACCESS_KEY']
set :ec2_url, ENV['EC2_URL']
set :ssh_options, { :user => "ubuntu", :keys=>[ENV['EC2_KEYFILE']]}
set :key, ENV['EC2_KEY']
set :key_file, ENV['EC2_KEYFILE']
set :ami, 'ami-52794c26'  #EC2 eu-west-1 32bit Lucid
set :instance_type, 'm1.small'
set :working_dir, '/mnt/work'

set :nhosts, 1
set :group_name, 'FloResCre_ChIPseq_data'

set :snap_id, `cat SNAPID`.chomp #ec2 eu-west-1 
set :vol_id, `cat VOLUMEID`.chomp #empty until you've created a new volume
set :ebs_size, 30  #Needs to be the size of the snap plus enough space for alignments
set :availability_zone, 'eu-west-1a'  #wherever the ami is
set :dev, '/dev/sdf'
set :mount_point, '/mnt/data'


#start an instance
#cap EC2:start

#make a new EBS volume and mount it
#cap EBS:create
#cap EBS:attach
#cap EBS:format_xfs
#cap EBS:mount_xfs



#why the hell doesn't this work.
desc "Upload data files"
task :upload_data, :roles => group_name do
  files = [
           "C18 H3K9ac_CME143_s_8_export.zip",
           "D4 H3K9ac_CME141_s_6_export.zip",  
           "FloResCre (C18) H4ac_CME117_s_2_export.zip",
           "FloRes H4acs_CME118_3_export.zip",
           "C18 input_CME142_s_7_export.zip",   
           "D4 input_CME140_s_5_export.zip",
           "FloResCre (C18) Input_CME116_s_5_export.zip",
           "README"
  ]

  files.each do |f|
    upload(f, "#{mount_point}/#{f}", :via => :scp) 
  end
end
before 'upload_data', 'EC2:start'


# cap EBS:snapshot
# cap EBS:unmount
# cap EBS:detach
# cap EBS:delete 
# cap EC2:stop

